### ISSUE TITLE
no graphic output on TBT screen

### ISSUE THREAD

**Issue by dongyj1987** [osy86/HaC-Mini#16] opened 2019-07-16 08:12 UTC
I installed 10.14.5 mojave on the hades canyon and it works well with my 1080p monitor. but when i use a 5k monitor with the thunderbolt plug, there's no graphic output at all and the screen is black. but the loudspeaker inside the monitor works so i think maybe the tbt device is connected.
my 5k monitor is lg ultrafine 5k and it is designed for macos, u can find it in the apple store and i'm sure it should be working perfectly with a real mac. the resolution is 5120x2880. it can connects only with a thunderbolt plug, no dp or hdmi. it works well in windows 10 at 5120x2880@60Hz
 except the HID light sensor so it cannot adjust the brightness automatically. 
It would be perfect if the screen goes well for this set.

**Comment by dongyj1987** [comment] 2019-07-16 08:37
I've already got the TB3 security setting from its default to the legacy mode in the bios

**Comment by osy86** [comment] 2019-07-16 15:58
Duplicate of #15 

Let's keep the conversation there.

**Closed by osy86** 2019-07-16 15:58 UTC
Labels: duplicate
