### ISSUE TITLE
wake up issue with 2.13

### ISSUE THREAD

**Issue by yuningchina** [osy86/HaC-Mini#349] opened 2020-10-16 08:13 UTC
When I update the installer to 2.13. I got wake up problem. I can not wake up with the mouse or keyboard.

OS: 10.15.7
USB: USB hub, mouse, keyboard, camera link to 4 usb(blue),  a type-c audio link to thunderbolt 

I got this message 

$ log show --last 1d | grep "Wake reason"
2020-10-16 09:48:26.317344+0800 0x12abe    Default     0x0                  132    0    powerd: [powerd:sleepWake] Wake reason: "<private>"  identity: "<private>"
2020-10-16 09:48:52.573937+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: RTC (Alarm)
2020-10-16 09:48:52.573938+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: RTC (Alarm)
2020-10-16 10:24:18.981677+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PXSX RP10 PXSX RP11 PXSX RP12 PXSX RP13 PXSX PXSX RP04 PXSX RP06 PXSX RP07 PXSX RP08 PXSX RP17 PXSX RP18 PXSX RP19 PXSX RP20 P
2020-10-16 10:24:18.981678+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PXSX RP10 PXSX RP11 PXSX RP12 PXSX RP13 PXSX PXSX RP04 PXSX RP06 PXSX RP07 PXSX RP08 PXSX RP17 PXSX RP18 PXSX RP19 PXSX RP20 P
2020-10-16 13:46:52.780648+0800 0x1903     Default     0x0                  132    0    powerd: [powerd:sleepWake] Wake reason: "<private>"  identity: "<private>"
2020-10-16 13:47:29.030090+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: XDCI USBW (User)
2020-10-16 13:47:29.030091+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: XDCI USBW (User)

<img width="561" alt="iShot2020-10-16 16 11 45" src="https://user-images.githubusercontent.com/43426527/96231428-4d529400-0fca-11eb-827d-03134c43f8d4.png">

**Comment by osy86** [comment] 2020-10-16 08:27
Duplicate of #348

**Closed by osy86** 2020-10-16 08:27 UTC
Labels: duplicate
