### ISSUE TITLE
Cannot boot from the USB installer.

### ISSUE THREAD

**Issue by zdaxie** [osy86/HaC-Mini#70] opened 2019-10-09 18:07 UTC
**Describe the bug**
I followed the instructions to create the USB installer, and manually copy the EFI folder to the EFI partition.(I cannot use the pkg file to finish my installation.) But I failed when I tried to boot from the USB installer. All I can see is a dark screen. So sad... Are there any possible settings that I missed? Like the BIOS version or something?

**Environment:**
 - Running OSX version: None
 - Target drive OSX version: 10.14/10.15(Both I have tried.)
 - HaC Mini installer version: 2.1(Manually Install)

**Comment by vitolio00** [comment] 2019-10-09 21:20
> Boot: Settings for boot screen (leave as-is unless you know what you're doing)
> ShowPicker: YES
> Shows OpenCore's UI, needed for seeing your available drives or set to NO to follow default option
> UsePicker: YES
> Uses OpenCore's default GUI, set to NO if you wish to use a different GUI
[`https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/config.plist/coffee-lake`](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/config.plist/coffee-lake)

**Comment by zdaxie** [comment] 2019-10-10 03:13
@vitolio00 Thanks a lot! I will give it a try!

**Comment by osy86** [comment] 2019-10-12 20:32
Duplicate of #56

**Closed by osy86** 2019-10-12 20:32 UTC
Labels: installer
