### ISSUE TITLE
OS need some time to warm up

### ISSUE THREAD

**Issue by fkpwolf** [osy86/HaC-Mini#302] opened 2020-08-03 10:59 UTC
**Describe the bug**
After login, Some common operations like opening Finder or Chrome are slow. I can see the loading icon. But after a few minutes, OS becomes much faster. I haven't installed program which will run on system boot. How to debug and tune this kind of issue?

**Expected behavior**
Boot process maybe slow, it is acceptable. But after login, OS should be usable and interactive to user input.

**Configuration**
- HaC Mini version [e.g: 2.0]: 
- OSX version [e.g: 10.14.6]: 
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Marvelll NVME
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Samsung DDR4-2666 16GB
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices:

**Comment by osy86** [comment] 2020-08-03 16:02
Seems like an OS X issue to me. Next time it happens run “spindump” in terminal and post the logs.

**Comment by candyrock** [comment] 2020-08-03 19:46
> Seems like an OS X issue to me. Next time it happens run “spindump” in terminal and post the logs.

I think due to Macos issue.

**Comment by fkpwolf** [comment] 2020-08-16 02:17
> > Seems like an OS X issue to me. Next time it happens run “spindump” in terminal and post the logs.
> 
> I think due to Macos issue.

But. it boots up smooth on my intel i5 8400 machine(without dedicate gpu).

**Comment by lf-openthos** [comment] 2020-08-17 04:31
I've the same issue. But it seems gone these days and I cannot figure wether it's about OC or MacOS itself.

**Comment by osy86** [comment] 2020-08-19 04:16
I can't reproduce. Please post `spindump` log next time you experience this or I will close the issue.

**Comment by fkpwolf** [comment] 2020-08-19 10:40
[spindump.txt](https://github.com/osy86/HaC-Mini/files/5095821/spindump.txt)
file attached.

**Comment by osy86** [comment] 2020-08-19 16:20
This was taken while it was slow?

**Comment by fkpwolf** [comment] 2020-08-20 00:30
> This was taken while it was slow?

yes, I ran the command just after login. And after upgrade to 10.15.6, looks it much slower to warm up system. I have a NVME book disk.
[spindump.txt](https://github.com/osy86/HaC-Mini/files/5099989/spindump.txt)

**Comment by fkpwolf** [comment] 2020-08-24 12:31
Actually every app ran slowly when system warm up, like Finder, Evernote.

I found WindowServer process takes a lot cpu. `log stream --predicate '(process == "WindowServer")' --debug` reports lots of error every second:
    
    On display 0x78c92519, surface is not detached, CoreDisplay is detached

I am not sure if it is related with this issue.

**Closed** 2020-09-03 14:37 UTC
