### ISSUE TITLE
System crash after idle hours

### ISSUE THREAD

**Issue by btbxbob** [osy86/HaC-Mini#238] opened 2020-04-19 13:58 UTC
**Describe the bug**
Disabled hibernate, but idle after 1 or 2 hours the system crashed.
after crash the system reboot and left a crash report, attached below

**Expected behavior**
stay idle and won't crash

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.6
- OSX version [e.g: 10.14.6]: 10.15.4
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Lexar 1TB SSD Media, NVMe
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: n/a
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Kingston. DDR4-2666 16GB 
- Second DIMM model (if installed): Kingston. DDR4-2666 16GB 
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4k
- Any TB3 devices: no
- Any USB devices: Mouse, keyboard

**Modifications**
none

**Panic log**
panic(cpu 2 caller 0xffffff7f912cf231): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0x17 VID=0xffff DID=0xffff
. FW Revision=V1.7.0\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5320
Backtrace (CPU 2), Frame : Return Address
0xffffff83bd323a40 : 0xffffff800d7215cd 
0xffffff83bd323a90 : 0xffffff800d85a3c5 
0xffffff83bd323ad0 : 0xffffff800d84bf7e 
0xffffff83bd323b20 : 0xffffff800d6c7a40 
0xffffff83bd323b40 : 0xffffff800d720c97 
0xffffff83bd323c40 : 0xffffff800d721087 
0xffffff83bd323c90 : 0xffffff800dec2c7c 
0xffffff83bd323d00 : 0xffffff7f912cf231 
0xffffff83bd323d20 : 0xffffff7f912ba362 
0xffffff83bd323e80 : 0xffffff7f912ba1a9 
0xffffff83bd323ec0 : 0xffffff800d763545 
0xffffff83bd323f40 : 0xffffff800d763071 
0xffffff83bd323fa0 : 0xffffff800d6c713e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[3DB9BFC6-422F-39A2-A445-AB2732CE5BFC]@0xffffff7f912ac000->0xffffff7f912eefff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[5EF51D44-9FC7-357F-9FB7-3468FD748382]@0xffffff7f8e7e1000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f8e131000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[6B3E9057-454A-3220-8AE3-424808CDA9E5]@0xffffff7f8ea64000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[425BC668-32EC-368C-B4EB-CF8510846BEE]@0xffffff7f8e310000
            dependency: com.apple.iokit.IOReportFamily(47)[337B24B2-0261-3521-8D1B-23387FC1D657]@0xffffff7f8e510000

BSD process name corresponding to current thread: kernel_task
Boot args: alcid=11 -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x000000000d400000
Kernel text base: 0xffffff800d600000
__HIB  text base: 0xffffff800d500000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 3751795980214

**Comment by osy86** [comment] 2020-04-19 14:29
Duplicate of #22

**Closed by osy86** 2020-04-19 14:29 UTC
Labels: duplicate
