### ISSUE TITLE
修复屏幕偶尔闪屏，修复部分分辨率重启系统后用闪屏

### ISSUE THREAD

**Issue by a13302211596** [osy86/HaC-Mini#80] opened 2019-10-17 15:15 UTC
独显ID：用四叶草自动获取，或者手动输入67DF00C0
<img width="1550" alt="9D05D146-845D-44D4-9437-F34F8090F676" src="https://user-images.githubusercontent.com/53515825/67022517-f0609b80-f133-11e9-949e-74c9da9fcf6b.png">
<img width="668" alt="4FFEE407-C79D-42FA-A375-F73E0D5AC7C2" src="https://user-images.githubusercontent.com/53515825/67022518-f191c880-f133-11e9-8daf-eae1e08d6388.png">
<img width="1279" alt="3645DB54-1695-49D6-BD53-B128B4921332" src="https://user-images.githubusercontent.com/53515825/67022542-fb1b3080-f133-11e9-85b2-ec456b9dc5b4.png">
<img width="1279" alt="E4121A07-6161-402D-BD84-320808C8B7D4" src="https://user-images.githubusercontent.com/53515825/67022552-fd7d8a80-f133-11e9-9fe5-bb4fa13ed4ba.png">
<img width="1279" alt="80160FC3-7B11-4903-A281-5428FC86EF05" src="https://user-images.githubusercontent.com/53515825/67022557-feaeb780-f133-11e9-8126-8f00e9254f35.png">
[Uploading EFI.zip…]()

**Comment by a13302211596** [comment] 2019-10-17 15:19
使用WhateverGreen驱动，开机会速度会变慢，并且出现闪屏问题
未使用WhateverGreen驱动，开机第二屏紫条，开机速度明显变快，使用四叶草自动获取独立显卡ID，闪屏问题能得到有效改善

**Comment by a13302211596** [comment] 2019-10-17 15:27
<img width="976" alt="87970A0D58F3D97DD0830919082BA26E" src="https://user-images.githubusercontent.com/53515825/67023571-995bc600-f135-11e9-80fb-f6649f01415f.png">

**Comment by deepmining** [comment] 2019-10-18 01:50
thank's a lot. You resolved my problem.

**Comment by jingquanquan2018** [comment] 2019-10-18 07:12
紫条问题可以解决吗？

**Comment by a13302211596** [comment] 2019-10-18 07:24
> 紫条问题可以解决吗？

安装osy86，2.2版本可以解决

**Comment by deepmining** [comment] 2019-10-18 11:52
我没有紫条问题

**Comment by deepmining** [comment] 2019-10-18 11:54
@osy86 4K artifacting/flickering problem after remove the WhateverGreen ,it resolved.

**Comment by osy86** [comment] 2019-10-26 22:35
@deepmining @a13302211596 I am not able to reproduce this fix. I still get flickering on 2560x1440 after sleep. Can one of you post your EFI directory so I can test? Also, what display ports are being used?

**Comment by rhtect** [comment] 2019-10-27 14:02
> 独显ID：用四叶草自动获取，或者手动输入67DF00C0
> <img alt="9D05D146-845D-44D4-9437-F34F8090F676" width="1550" src="https://user-images.githubusercontent.com/53515825/67022517-f0609b80-f133-11e9-949e-74c9da9fcf6b.png">
> <img alt="4FFEE407-C79D-42FA-A375-F73E0D5AC7C2" width="668" src="https://user-images.githubusercontent.com/53515825/67022518-f191c880-f133-11e9-8daf-eae1e08d6388.png">
> <img alt="3645DB54-1695-49D6-BD53-B128B4921332" width="1279" src="https://user-images.githubusercontent.com/53515825/67022542-fb1b3080-f133-11e9-85b2-ec456b9dc5b4.png">
> <img alt="E4121A07-6161-402D-BD84-320808C8B7D4" width="1279" src="https://user-images.githubusercontent.com/53515825/67022552-fd7d8a80-f133-11e9-9fe5-bb4fa13ed4ba.png">
> <img alt="80160FC3-7B11-4903-A281-5428FC86EF05" width="1279" src="https://user-images.githubusercontent.com/53515825/67022557-feaeb780-f133-11e9-8126-8f00e9254f35.png">
> Uploading EFI.zip…
你好  可以发一份完整的EFI吗 我发现按照您的修改之后雷电不能驱动。OC CLOVER 的都可以。我安装V2.2版本的启动黑屏  进不去引导界面

**Comment by rhtect** [comment] 2019-10-27 14:11
![image](https://user-images.githubusercontent.com/50864742/67635921-864faf80-f906-11e9-9f7e-79eb5c26a64d.png)
![image](https://user-images.githubusercontent.com/50864742/67635949-ab442280-f906-11e9-8a10-170f28167747.png)

**Comment by osy86** [comment] 2019-10-28 17:28
@deepmining @a13302211596 Can you post EFI.zip with graphics fix?

**Comment by a13302211596** [comment] 2019-11-01 21:54
@osy86 Hello, the latest version of blinking has been fixed，WhateverGreen1.3.4

**Comment by jarryji** [comment] 2019-11-03 06:22
> @osy86 Hello, the latest version of blinking has been fixed，WhateverGreen1.3.4
osy86 在问你要一下你的EFI完整文件夹(修复闪屏之后), 他可能需要看一下怎么解决这个闪屏问题的.

**Comment by xiaojy1983** [comment] 2019-11-04 08:04
@a13302211596 大哥，能分享一下EFI吗？升级WG1.3.4，我还是遇到闪屏。

**Comment by lisongzhou19** [comment] 2019-11-05 00:59
[CLOVER.zip](https://github.com/osy86/HaC-Mini/files/3806732/CLOVER.zip)
![Xnip2019-11-05_08-58-01](https://user-images.githubusercontent.com/56990075/68170368-6e34fb80-ffaa-11e9-90ab-ac25a3a7c177.jpg)

It should be this, but I have not tested it, I hope it will be useful to you.

**Comment by lisongzhou19** [comment] 2019-11-05 01:02
2.bios设置
将Bios更新到最新版本; 禁用“Secure Boot”; 禁用“IntelIGD(集显）”; 禁用“VT-d”; 设置“Wake on LAN from S4/S5" to "Stay Off"; 启用“Boot Boot Devies First”

**Comment by xiaojy1983** [comment] 2019-11-05 01:50
> [CLOVER.zip](https://github.com/osy86/HaC-Mini/files/3806732/CLOVER.zip)
> ![Xnip2019-11-05_08-58-01](https://user-images.githubusercontent.com/56990075/68170368-6e34fb80-ffaa-11e9-90ab-ac25a3a7c177.jpg)
> 
> It should be this, but I have not tested it, I hope it will be useful to you.

THANKS!

**Comment by lisongzhou19** [comment] 2019-11-05 02:04
@osy86 
It should be this, but I have not tested it, I hope it will be useful to you.

**Comment by osy86** [comment] 2019-11-05 04:49
I still get flickers as described in #7 

I'm closing this ticket because there does not seem to be any outstanding issues here.

**Closed by osy86** 2019-11-05 04:49 UTC

**Comment by deepmining** [comment] 2019-11-22 05:45
[EFI.zip](https://github.com/osy86/HaC-Mini/files/3878092/EFI.zip) I am busy for a long time. I see it just now. I remove WhateverGreen kext from the EFI/OC/Kexts directory.  this is my efi folders .

**Comment by deepmining** [comment] 2019-11-22 05:46
@osy86

**Comment by hfharry** [comment] 2019-11-28 03:46
> [EFI.zip](https://github.com/osy86/HaC-Mini/files/3878092/EFI.zip) I am busy for a long time. I see it just now. I remove WhateverGreen kext from the EFI/OC/Kexts directory. this is my efi folders .

I followed your instruction and deleted WhateverGreen kext. It seems perfectly solved flickering issue. Besides, there is no side-effect caused by deleting kext found during 2 days test.

Ps: My monitor is LG UltraFine 4K 21.5' model. I'm using it under default HiDPI mode.

**Comment by lmshsqlc** [comment] 2019-11-28 03:50
> > [EFI.zip](https://github.com/osy86/HaC-Mini/files/3878092/EFI.zip) I am busy for a long time. I see it just now. I remove WhateverGreen kext from the EFI/OC/Kexts directory. this is my efi folders .
> 
> I followed your instruction and deleted WhateverGreen kext. It seems perfectly solved flickering issue. Besides, there is no side-effect caused by deleting kext found during 2 days test.
> 
> Ps: My monitor is LG UltraFine 4K 21.5' model. I'm using it under default HiDPI mode.

There’s an option on installing HaC-Mini to not include whatevergreen upon install. It also explained that removing whatevergreen can sometimes fix some flickering issue. @a13302211596 can you put this on the header so that everyone can see the solution? 可以把这个解释放在楼顶让大家看到吗，可以让大家有同样问题的话可以少走弯路。谢谢🙏

**Comment by xiaojy1983** [comment] 2019-11-29 06:22
> [EFI.zip](https://github.com/osy86/HaC-Mini/files/3878092/EFI.zip) I am busy for a long time. I see it just now. I remove WhateverGreen kext from the EFI/OC/Kexts directory. this is my efi folders .

Thanks. I tried to replace the EFI folder, but unfortunately, I still get flickering on 2560x1440 after sleep or logout.

**Comment by errorstack** [comment] 2019-12-04 02:48
> [EFI.zip](https://github.com/osy86/HaC-Mini/files/3878092/EFI.zip) I am busy for a long time. I see it just now. I remove WhateverGreen kext from the EFI/OC/Kexts directory. this is my efi folders .

It seems the flickering issue resolved after removing WhateverGreen kext. But I noticed the sidecar display could not work any more, and it recovered after I added the WhateverGreen kext back. So I gave up this solution.

BTW, WhateverGreen has a new release 1.3.5, anyone tried? Does it resolve the flickering issue?
