### ISSUE TITLE
macOS screen flashes green or pink randomly (idling or on YouTube, etc.)

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#250] opened 2020-04-28 05:46 UTC
**Description**
When in macOS and connected to 1 single 4k TV display, the system will experience briefly flashing or briefly flickering a colour (green, pink). This can happen _while idling_ and is absolutely most often in Chrome/Firefox when using sites that use video playback features (e.g. mousing over YouTube video icons and they start moving for the preview playback).

I have read that using various apps to limit the display colour can help fix this problem with hackintoshes (DisplayMaestro or SwitchResX).

**Expected behavior**
No flickering or flashes of green.

**Configuration**
- HaC Mini version: 2.7 _OpenCore_
- OSX version: 10.14.6
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: Intel 760p series 1TB NVMe M.2 SSD (MacOS boot)
- Second SSD model and protocol: Samsung 970 Pro 512GB NVMe M.2 SSD (Windows 10 Pro)
- First DIMM model: DDR4-2400MHz Kingston HyperX 16GB
- Second DIMM model: DDR4-2400Hz Kingston HyperX 16GB
- Display port(s) used [e.g: USB-C, mini DP]: mDP 1 -> HDMI 2.0 adapter -> HDMI 2.0 cable
- Display resolution: 4k60 (3840x2160) to 55inch Sony TV
- Any TB3 devices: AKiTiO Node Pro (housing ElGato 4k60 mk2 for now)
- Any USB devices: Logitech unifying receiver, UPS backup, Xbox One wireless controller adapter, AKiTiO 10Gbps USB-C enclosure with 8TB NAS HDD (using USB-C to C cable). Logitech MX Master 2S and Logitech K830.

**Modifications**
No modifications aside from always use boot picker and give 10 seconds for the boot picker window. I have installed an Intel AX200 M.2 WiFi module for use with WiFi 6 and BT 5.0 (and bluetooth in BIOS). I have _not yet_ installed the IntelBluetooth kext from zxystd. For the install pkg I selected the _radeon_ codec and _not intel_ codec.

**Panic log**
none

**_NOTES_**
In Windows 10 Pro, I had been noticing random booting to a garbled screen of pixels (think of static from a missing channel for old TV). Turns out it was the HDCP setting under Radeon settings. In Windows I have disabled it, and now the mDP works perfectly every time!! (I also cannot achieve any overclock to the GPU under Windows... which is OK, before using HaC mini I was able to get 1310 GPU and 870 VRAM stable...)

Screen colour flickering does not happen in Windows. Is it possible for there to be any HDCP setting for macOS?

**Comment by osy86** [comment] 2020-04-28 17:24
Duplicate of #7

**Comment by osy86** [comment] 2020-04-28 17:25
I think. Please try the workaround proposed at the very end of that issue and let me know.

**Comment by osy86** [comment] 2020-06-16 17:22
Closing due to lack of response.

**Closed by osy86** 2020-06-16 17:22 UTC
Labels: duplicate
