### ISSUE TITLE
Patching OSX install usb fails at "Running Package Scripts"

### ISSUE THREAD

**Issue by jonseppanen** [osy86/HaC-Mini#63] opened 2019-09-25 02:11 UTC
**Describe the bug**
After following clean install directions while building a new install on another machine, the patcher failes at "Running Package Scripts".
I notice that there is an efi drive mounted on the desktop with an ESP folder, that seems to be symlinked to itself, so it just keeps opening itself forever.

**Expected behavior**
Patching should complete

**Environment:**
 - Running OSX version: OSX mojave on patching pc
 - Target drive OSX version:  OSX mojave from app store
 - HaC Mini installer version: Latest test release

**Additional context**
I can probably manually get the installer patched if I knew the manual steps to do so. Should they be documented somewhere just in case?

**Logs**
The log states that install failed on postinstall.sh. It is likely efi related.

**Comment by osy86** [comment] 2019-09-25 02:12
Check `diskutil list`. You may not have a EFI partition. Did you format as directed? https://osy.gitbook.io/hac-mini-guide/installation-guide/installation#creating-osx-installer

**Comment by jonseppanen** [comment] 2019-09-25 02:23
Formatted as directed, GUID partition map with MacOS extended journaled.

Redoing again. Im assuming following the guide creates the EFI partition on the USB?

**Comment by osy86** [comment] 2019-09-25 02:25
It's important that you're formatting the disk and not an existing volume on the disk. The latter way won't create the EFI partition.

**Comment by jonseppanen** [comment] 2019-09-25 02:28
Got it. I'm sure I did that but I could have just blindly sped through. Will report back!

**Comment by jonseppanen** [comment] 2019-09-25 03:03
Just tried twice more making sure the Device and not the volume was selected, same result. Do you think the official osx installer creator is somehow broken?

**Comment by osy86** [comment] 2019-09-25 03:11
It’s not the OS X creator that makes the EFI. It’s disk utility. Right after formatting do a diskutil list and make sure you see a 200MB partition as the first one and it should say GUID partition scheme.

**Comment by jonseppanen** [comment] 2019-09-25 03:20
The partition definitely exists when I do diskutil list.

**Comment by osy86** [comment] 2019-09-25 03:47
Okay then you’ll have to attach install.log for me to see what the issue is.

**Comment by jonseppanen** [comment] 2019-09-25 04:04
Just did the following on another machine (13" macbook pro touchbar)

- Download Mojave from the App Store
- Format fresh USB drive with GUID and OSX externalled, being sure to select the device
- EFI partition exists
- Run the create installer utility for Mojave
- Run the latest install patcher

Exact same error, exact same place. Maybe your script is making a symlink inside the efi partition incorrectly?

I have attached the log as well.
[install-truncated.log](https://github.com/osy86/HaC-Mini/files/3650486/install-truncated.log)

**Comment by jonseppanen** [comment] 2019-09-25 04:33
Attempting to run the installer results in no bootable partition found. Looks like the efi partition is being cleared out?

**Comment by jonseppanen** [comment] 2019-09-25 05:38
Tried with yet another USB on another machine, same issue.

**Comment by K-telj** [comment] 2019-09-25 16:26
just an fyi, I am off for a few days and was trying the opencore on a new install and got this issue here as well.

**Comment by jonseppanen** [comment] 2019-09-26 00:31
Tried with an older version of Mojave installer on yet another machine, same problem. EFI folder ends up empty after the patching fails. Is there a pre-built efi folder I could download perhaps?

**Comment by osy86** [comment] 2019-09-26 00:32
There is, check the releases.

**Comment by jonseppanen** [comment] 2019-09-26 01:45
Extracted to an EFI folder on the efi partition. Shows as bootable in bios, but only results in a black screen on boot.

**Comment by zdaxie** [comment] 2019-09-30 15:41
Also encountered this problem. I wanna know do you have any solutions now? Very thanks!

**Comment by osy86** [comment] 2019-09-30 15:45
Sorry been super busy. You can use the EFI zip without the installer for now.

**Comment by zdaxie** [comment] 2019-09-30 15:46
OK, I will try. Thanks again!

**Comment by jonseppanen** [comment] 2019-09-30 23:30
As per my comment, extracting EFI zip doesnt work.

**Comment by osy86** [comment] 2019-10-01 00:25
Have you tried the troubleshooting tips from the guide?

**Comment by jonseppanen** [comment] 2019-10-01 00:56
Which one?

1. Get into boot picker menu: 
Usb wont boot in any way, black screen, no boot picker menu
2. Reset NVRAM:
See above. Its a fresh machine out of box nonetheless
3. Reinstall Hac Mini:
Cant install Hac Mini the first time from USB (this is what the issue is about)
4: Disable Any Third Party Extensions:
See above.
5: Enable verbose boot:
See above.

**Comment by osy86** [comment] 2019-10-01 01:23
When you press F10, do you see an entry for your USB drive?

**Comment by jermafenser** [comment] 2019-10-01 21:58
I have run into a similar issue with the v2.1 installer.  Usage of the v2.0 installer completed patching of the usb device successfully.

**Comment by jonseppanen** [comment] 2019-10-02 00:23
> Extracted to an EFI folder on the efi partition. Shows as bootable in bios, but only results in a black screen on boot.

**Comment by jonseppanen** [comment] 2019-10-02 01:09
Using v2.0 of OC shows a boot entry but will not boot from it in any way, just skips on through to the existing installed linux os.
An EFI folder is now present in the EFI partition when using the 2.0 patcher, fyi.

**Comment by hepto** [comment] 2019-10-02 19:10
Also seeing this issue, and my installer log is the same as @jonseppanen's.

There is some good logging going on, and looks to me that it's `PlistBuddy` bombing out at line 46 of `copy_serial.sh` as they are the last two lines logged before failure ...

```
2019-09-25 13:21:06+10 MBAFUs-iMac installd[1192]: ./postinstall: Set: Entry, ":PlatformInfo:Generic:SystemSerialNumber", Does Not Exist
2019-09-25 13:21:06+10 MBAFUs-iMac installd[1192]: ./postinstall: File Doesn't Exist, Will Create: /Volumes/Install macOS Mojave/tmp/EFIROOTDIR/EFI/OC/config.plist
```

The very next line should simply echo `$MLB` which does not occur, so the script must exit with a failure code at that point, which causes `postinstall.sh` to fail, and thus the installer.

I will keep digging - I've not gone backwards far enough to see what has/hasn't occurred up to this point - maybe something simple like it can't write the file.

**Comment by osy86** [comment] 2019-10-02 19:19
After failed installation on a freshly formatted USB, can you mount USB’s EFI partition and post the contents here? It appears that config.plist wasn’t installed properly.

**Comment by hepto** [comment] 2019-10-02 19:42
No worries.  With diskutil output also for completeness:

**Before** running installer:

```
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *64.2 GB    disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS Install macOS Mojave    63.8 GB    disk2s2
```

Contents of EFI:

```
ls -al /Volumes/EFIGH/
total 3
drwxrwxrwx@ 1 hepto  staff  512  2 Oct 20:37 .
drwxr-xr-x+ 6 root   wheel  192  2 Oct 20:37 ..
drwxrwxrwx  1 hepto  staff  512  2 Oct 20:37 .Spotlight-V100
drwxrwxrwx  1 hepto  staff  512  2 Oct 20:37 .fseventsd
```

**After** installer fails:

```
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *64.2 GB    disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS Install macOS Mojave    63.8 GB    disk2s2
```

```
ls -al /Volumes/ESP/
total 3
drwxrwxrwx@ 1 hepto  staff  512  2 Oct 20:37 .
drwxr-xr-x+ 6 root   wheel  192  2 Oct 20:39 ..
drwxrwxrwx  1 hepto  staff  512  2 Oct 20:37 .Spotlight-V100
drwxrwxrwx  1 hepto  staff  512  2 Oct 20:39 .fseventsd
```

So, empty :(

Where in the Installer does the copy take place?

**Comment by hepto** [comment] 2019-10-02 19:47
Note that if I **untick** the backup option under `Customise`, I then get the recursive symlink mentioned earlier:

```
ls -al /Volumes/ESP/
total 4
drwxrwxrwx@ 1 hepto  staff  512  2 Oct 20:43 .
drwxr-xr-x+ 6 root   wheel  192  2 Oct 20:39 ..
drwxrwxrwx  1 hepto  staff  512  2 Oct 20:37 .Spotlight-V100
drwxrwxrwx  1 hepto  staff  512  2 Oct 20:39 .fseventsd
lrwxrwxrwx  1 hepto  staff   12  2 Oct 20:43 ESP -> /Volumes/ESP
```

**Comment by osy86** [comment] 2019-10-02 19:49
Can you try this one? I found a bug in the install script. 
[HaCMini.zip](https://github.com/osy86/HaC-Mini/files/3683073/HaCMini.zip)

**Comment by hepto** [comment] 2019-10-02 20:05
I'm sorry, but identical results.  Attached is the log.

[Installer Log 2-Oct-2019.txt](https://github.com/osy86/HaC-Mini/files/3683111/Installer.Log.2-Oct-2019.txt)

**Comment by osy86** [comment] 2019-10-02 20:16
[HaCMini.pkg.zip](https://github.com/osy86/HaC-Mini/files/3683149/HaCMini.pkg.zip)
It seems like OSX installer has a bug. It assumes “/tmp” always points to “/private/tmp”. I’ve changed the path please try again.

**Comment by hepto** [comment] 2019-10-02 20:22
Ok, give me an hour or so. Thanks for this - just started looking at this project but once I get familiar with it I'd be happy to help.

**Comment by hepto** [comment] 2019-10-02 21:40
Bit further this time - EFI volume is now populated and the drive recognised by UEFI, but alas I now also get the black screen issue on boot.  Have not troubleshot yet, probably needs a new issue.

Actually, the installer still failed as it could not unmount the EFI partition at the end of `postinstall.sh` as `mds` had hold of it (Spotlight).  I was eager to try the USB so I ejected manually.  Will try a couple more times to see if it is a persistent issue - probably the script should wait for the unmount to succeed.

**Comment by osy86** [comment] 2019-10-02 21:47
I think black screen should be bypassed by triggering opencore picker menu. See if you can find OS X installer as an entry.

**Comment by hepto** [comment] 2019-10-02 22:06
How does one open  the opencore picker menu?

**Comment by osy86** [comment] 2019-10-02 22:11
https://osy.gitbook.io/hac-mini-guide/post-installation/support#getting-into-boot-picker-menu

**Comment by hepto** [comment] 2019-10-02 22:17
Ha! Sorry I should search. < slaps wrists >

Actually, I got it to come up by adding `ShowPicker` `True` to the OC plist.

So now installing! 👍🏻

**Comment by K-telj** [comment] 2019-10-06 19:17
Ive been encountering all the issues listed throughout this thread, and am stalled at getting anything to show up at f10 - boot menu, theres a OS X option but when I choose it repeatedly its goes back to menu, and this is with all sorts of alt key taps - hold - tap/holds. I am using the latest edited https://github.com/osy86/HaC-Mini/issues/63#issuecomment-537661798
version, it fails the install writing to the usb with the "Patch OSX installer" option, and succeeds with this option off. It never gets to the boot picker or install as of yet.

**Comment by osy86** [comment] 2019-10-12 20:21
The original issue described has been fixed in the latest installer. Anyone with additional problems should file a new ticket and fill in the requested information.

**Closed by osy86** 2019-10-12 20:21 UTC
Labels: installer
