### ISSUE TITLE
minidp and hdmi double 4k output flicker

### ISSUE THREAD

**Issue by bjgowlk** [osy86/HaC-Mini#212] opened 2020-03-22 02:15 UTC
single 4k is perfect, but when I connect two 4k moniters(dell 2718q) via miniDP and HDMI, two screens are flikering when I move my mouse, wish sombody could help!

**Comment by bjgowlk** [comment] 2020-03-22 02:21
Does anybody meet the same problem?

**Comment by kennymustdie** [comment] 2020-03-22 10:49
Hi, i have not double 4k at the moment. One 4k on DP and a 2K on HDMI. I have in some Resolution the same Prolbem. If i choose the resoluition in "lower Quality" it works. To get there hold the alt key wenn you klick on the resoluiton field in Diplsy Settings.

**Comment by psychic69** [comment] 2020-03-24 02:17
I am using 2 LG 4K displays (tried freesync on and off) both in DP ports, when I plug in the second, the screen flickering is active.  I can say if I put lower resolution settings that the flickering goes away however since these are not native resolution the text is fuzzy and interpolated.  Please examine this dual 4K monitor issue.  Thanks

**Comment by ccsnake** [comment] 2020-03-27 05:04
I have same problem.

**Comment by KrisCris** [comment] 2020-03-30 04:52
Same problem. Not even necessarily need dual 4k displays to trigger this issue, like mine is 4k + 2k..

**Comment by Yrp** [comment] 2020-03-30 17:59
Same problem. one is p2715Q, another is u3219Q, Only one is perfect. But two is plugged in miniDP ports, the both screen begin flicker.

**Comment by psychic69** [comment] 2020-03-30 21:46
I reduced the resolution using hidden alt modes, no more flickering.  I cant tell for sure but there may be some overscan that is going on and doesnt look like a framebuffer overflo however cant be sure:

AMD Radeon RX Vega M GL:

  Chipset Model:	AMD Radeon RX Vega M GL
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67df
  Revision ID:	0x00c2
  Metal:	Supported
  Displays:
LG Ultra HD:
  Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
  UI Looks like:	2560 x 1440 @ 60 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	Thunderbolt/DisplayPort
LG Ultra HD:
  Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
  UI Looks like:	2560 x 1440 @ 60 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	Thunderbolt/DisplayPort

**Comment by Yrp** [comment] 2020-03-31 03:11
I found that plugging in **three** 4k displays shows OK, **not flicker**,  two using miniDP, and one using a lightning port. But plugging in **two** 4k monitors, whether it is two miniDP, one is miniDP, one is thunder and lightning port all will **flicker**.

Could someone plug in **three** 4k monitors to test it out?

**Comment by KrisCris** [comment] 2020-03-31 04:00
> I found that plugging in **three** 4k displays shows OK, **not flicker**, two using miniDP, and one using a lightning port. But plugging in **two** 4k monitors, whether it is two miniDP, one is miniDP, one is thunder and lightning port all will **flicker**.
> 
> Could someone plug in **three** 4k monitors to test it out?

I can confirm that! Seems 3 display output can solve this problem... No idea why.

https://github.com/osy86/HaC-Mini/issues/172#issuecomment-578758912

**Comment by Yrp** [comment] 2020-03-31 04:27
> > I found that plugging in **three** 4k displays shows OK, **not flicker**, two using miniDP, and one using a lightning port. But plugging in **two** 4k monitors, whether it is two miniDP, one is miniDP, one is thunder and lightning port all will **flicker**.
> > Could someone plug in **three** 4k monitors to test it out?
> 
> I can confirm that! Seems 3 display output can solve this problem... No idea why.
> 
> [#172 (comment)](https://github.com/osy86/HaC-Mini/issues/172#issuecomment-578758912)

One or three 4k monitors display perfectly. It may be normal to insert a few monitors.
Plug in three 4k monitors for perfect display, then unplug one of them. The remaining two monitors are also perfect.
I have no idea about this. 
And why?

**Comment by fkpwolf** [comment] 2020-04-14 15:01
same problem

**Comment by BD5HTY** [comment] 2020-04-21 13:28
> > > I found that plugging in **three** 4k displays shows OK, **not flicker**, two using miniDP, and one using a lightning port. But plugging in **two** 4k monitors, whether it is two miniDP, one is miniDP, one is thunder and lightning port all will **flicker**.
> > > Could someone plug in **three** 4k monitors to test it out?
> > 
> > 
> > I can confirm that! Seems 3 display output can solve this problem... No idea why.
> > [#172 (comment)](https://github.com/osy86/HaC-Mini/issues/172#issuecomment-578758912)
> 
> One or three 4k monitors display perfectly. It may be normal to insert a few monitors.
> Plug in three 4k monitors for perfect display, then unplug one of them. The remaining two monitors are also perfect.
> I have no idea about this.
> And why?

same problem

**Comment by BD5HTY** [comment] 2020-04-23 15:14
I bought an HDMI emulator, which perfectly solved this problem.
Double 4K will no longer flicker.
[https://my.unoc.cn/downloads/hdmi.jpeg](url)

**Comment by deftdawg** [comment] 2020-04-28 04:08
This is a duplicate of #7 and should be closed as such... please follow that bug and try the software fix that osy86 is working on.

**Comment by osy86** [comment] 2020-04-28 23:12
Duplicate of #7

**Closed** 2020-04-28 23:12 UTC
Labels: duplicate
