### ISSUE TITLE
Portable 4k display over USB-C randomly flickering.

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#168] opened 2020-01-21 10:55 UTC
**Describe the bug**
A 4K 15.6 inch portable display over USB-C cable, using DisplayPort. (both side are USB-C).
![Screen Shot 2020-01-21 at 6 34 11 PM](https://user-images.githubusercontent.com/38860226/72797752-acbe8600-3c7c-11ea-93bc-acf139a9c450.png)

This display works fine with my windows laptop, and a 13inch 2018 MBP. However, when I connect that to my HaC Mini, it randomly flickers(turns white or something within a second and then backs to normal, but keeps flickering approx. every 5 minutes). 

And this flickering seems can be affected by the connection of my DELL 2K display: When both display are connected, the flickering become more frequently - it flickers every second but still can display images. And if I set my DELL display to 720P or 2048*1152, the flickering decreased, as the first situation.

(I forced my DELL display to using the HiDPI. But even with the vanilla 2K resolution, that 4K one still flickers constantly.)

**Expected behavior**

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.5
- OSX version [e.g: 10.14.6]: 10.15.2
- NUC model [e.g: NUC8i7HNK]: HVK
- Boot SSD model and protocol : NVMe
- Second SSD model and protocol : SATA
- First DIMM model : HyperX impact 16gb 2666
- Display port(s) used [e.g: USB-C, mini DP]: mini DP, USB-C
- Display resolution(s) [e.g: 4K, 5K]: 2K, 4K.
- Any TB3 devices: HP TB3 Dock.
- Any USB devices: keyboard, external hard drive, Logitech G receiver.

**Modifications**
None

**Panic log**
No idea how to get it.

**Comment by osy86** [comment] 2020-01-21 17:12
Yeah this is probably the same issue as #7 I still don’t know the cause. Can you try other resolutions and see if that helps?

**Comment by KrisCris** [comment] 2020-01-22 04:38
> Yeah this is probably the same issue as #7 I still don’t know the cause. Can you try other resolutions and see if that helps?

I could only find some resolutions that reduce flickering frequency, but no way to stop it even only using the 4k one at 1080p with HiDPI enabled.

**Comment by osy86** [comment] 2020-01-22 05:03
What about different refresh rates?

**Comment by KrisCris** [comment] 2020-01-22 07:41
> What about different refresh rates?

I don't think I can modify the refresh rate..
![截屏2020-01-22下午3 40 56](https://user-images.githubusercontent.com/38860226/72874708-96bcce00-3d2d-11ea-916f-b094c6ca1231.png)

**Comment by osy86** [comment] 2020-01-22 09:15
Try https://www.madrau.com/

**Comment by KrisCris** [comment] 2020-01-22 09:25
> Try https://www.madrau.com/

But the display is already running at 60HZ..

**Comment by KrisCris** [comment] 2020-01-22 13:03
> > Yeah this is probably the same issue as #7 I still don’t know the cause. Can you try other resolutions and see if that helps?
> 
> I could only find some resolutions that reduce flickering frequency, but no way to stop it even only using the 4k one at 1080p with HiDPI enabled.

Then I found that if I using 1680*945 on my portable display, this issue can be solved. Sadly this approach made every content too big for me.

BTW, #80 said that this problem may be solved by removing WhateverGreen, so do we really need that kext?

**Comment by osy86** [comment] 2020-01-22 17:13
Try it

**Comment by KrisCris** [comment] 2020-01-27 05:55
> Try it

Unfortunately, removing WG doesn't help. Besides, disabled IGPU in BIOS with WG, AMD codec installed doesn't help either.

**Comment by osy86** [comment] 2020-01-27 05:57
What about rotating the display 180 degrees? For some reason that stopped the flickering on my machine.

**Comment by KrisCris** [comment] 2020-01-27 06:01
> What about rotating the display 180 degrees? For some reason that stopped the flickering on my machine.

No I don't think it can help. I have tried that a month before when I read some documents on it, still flickers.

**Comment by osy86** [comment] 2020-06-24 03:29
Closing as duplicate of #7

**Closed by osy86** 2020-06-24 03:29 UTC
Labels: duplicate
