### ISSUE TITLE
Polaris22Fixup do not fix the window bug in Bigsur 11.0.1？

### ISSUE THREAD

**Issue by 13months** [osy86/HaC-Mini#383] opened 2020-11-14 13:41 UTC
Polaris22Fixup do not fix the window bug in Bigsur 11.0.1 when using Polaris22Fixup（ V1.3.1）
Also there is some bug here.Double border on the The menu of finder.
Please update it.Thanks very much.

<img width="616" alt="99134870-a3166c80-265a-11eb-92b6-3a45b990bc41-2" src="https://user-images.githubusercontent.com/19258580/99148320-04bdf180-26c2-11eb-9bde-6f344248d2c6.png">
<img width="604" alt="截屏2020-11-14 21 39 56" src="https://user-images.githubusercontent.com/19258580/99148323-0ab3d280-26c2-11eb-89fb-92b5a0d6d028.png">

**Comment by osy86** [comment] 2020-11-14 15:02
Duplicate of #316

**Closed by osy86** 2020-11-14 15:02 UTC
Labels: duplicate
