### ISSUE TITLE
Anyone, who installed macOS Mojave 10.14.6 Supplemental Update? 

### ISSUE THREAD

**Issue by HorstBrack75** [osy86/HaC-Mini#28] opened 2019-08-08 16:36 UTC
Would it work? Would it be required? Might this even fix some of the Wakeup issues mentioned here?

**Comment by osy86** [comment] 2019-08-08 16:50
I haven’t had time recently but I believe it should work. I doubt it would fix any problems for us though. The causes for the problems are well documented here.

**Comment by K-telj** [comment] 2019-08-10 16:25
I did it, I don't notice any difference but my wake up sleep seems to be working pretty dependably these days even with the attached thunderbolt device sleeping and waking.

**Comment by osy86** [comment] 2019-08-19 17:19
Interesting, I’ll do more tests with it. Closing because there’s no outstanding issues.

**Closed by osy86** 2019-08-19 17:19 UTC
