### ISSUE TITLE
default password of "IT_Admin"

### ISSUE THREAD

**Issue by undoZen** [osy86/HaC-Mini#155] opened 2019-12-20 03:00 UTC
I used version 2.4 to install 10.15.2, the admin user "IT_Admin" has been created automatically, but I don't know its password. While on post-install guide it said this computer is under T-Mobile's control, is it normal?

Also I can't boot from local ssd, only from usb drive. in bios I can only get the only item of usb drive on boot page, when I try to install Clover Bootloader, the  Clover Configurator prompts me to input password, which I don't know.

**Comment by osy86** [comment] 2019-12-20 03:02
> the admin user "IT_Admin" has been created automatically

I have never heard of this before.

> While on post-install guide it said this computer is under T-Mobile's control, is it normal?

Where does it say that? I have also never heard of this before.

**Comment by undoZen** [comment] 2019-12-20 03:07
What?!

I used catalina installer downloaded from app store and HaCMini.pkg from github.

**Comment by osy86** [comment] 2019-12-20 03:09
There is no mention of T-Mobile anywhere on the guide. I have no idea what "IT_Admin" is. Please make sure your computer isn't infected with a virus.

**Comment by undoZen** [comment] 2019-12-20 03:12
I'll try to install again later, if it occurs again I'll take a screenshot to post here.

I use DW1820A, can I remove it to install then install back after I finished installation, will the drivers be ok this way?

**Comment by osy86** [comment] 2019-12-20 03:13
Shouldn't be an issue.

**Comment by osy86** [comment] 2019-12-20 20:40
Closing due to lack of issue with the actual install

**Closed by osy86** 2019-12-20 20:40 UTC

**Comment by alexleisyd** [comment] 2020-01-09 23:42
I have encountered with this issue before. The cause is the MacOS image. Somehow the App Store gave me the T-Mobile image instead of the standalone one. I used another Mac and the correct image was downloaded.
