### ISSUE TITLE
The boot speed is very slow

### ISSUE THREAD

**Issue by LockVer** [osy86/HaC-Mini#320] opened 2020-08-24 17:52 UTC
Newly installed Big Sur，It takes about five minutes for the system to start up。
hacmini:2.11

**Comment by osy86** [comment] 2020-08-24 18:13
Every time or just first boot?

**Comment by LockVer** [comment] 2020-08-24 23:46
> Every time or just first boot?

every time 
It's also very slow to turn off. It takes about 15 to 30 seconds

**Comment by osy86** [comment] 2020-08-24 23:57
When you opened a ticket, there was a lot of information that you did not provide. I’ll ask for them again.

```
**Configuration**
- HaC Mini version [e.g: 2.0]: 
- OSX version [e.g: 10.14.6]: 
- NUC model [e.g: NUC8i7HNK]: 
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: 
- Any USB devices: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.
```

**Comment by LockVer** [comment] 2020-08-25 00:05
HaC Mini version [e.g: 2.0]: 2.11
- OSX version [e.g: 10.14.6]: 11
- NUC model [e.g: NUC8i7HNK]: nuc8i7hvk
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: sn750 512g
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: crucial ddr4-2666 8g
- Second DIMM model (if installed): crucial ddr4-2666 8g
- Display port(s) used [e.g: USB-C, mini DP]: mini-dp
- Display resolution(s) [e.g: 4K, 5K]: 4k 95hz
- Any TB3 devices: 
- Any USB devices: 

config. plist no changes

**Comment by LockVer** [comment] 2020-08-25 00:06
> When you opened a ticket, there was a lot of information that you did not provide. I’ll ask for them again.
> 
> ```
> **Configuration**
> - HaC Mini version [e.g: 2.0]: 
> - OSX version [e.g: 10.14.6]: 
> - NUC model [e.g: NUC8i7HNK]: 
> - Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 
> - Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
> - First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
> - Second DIMM model (if installed): 
> - Display port(s) used [e.g: USB-C, mini DP]: 
> - Display resolution(s) [e.g: 4K, 5K]: 
> - Any TB3 devices: 
> - Any USB devices: 
> 
> **Modifications**
> List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.
> ```

HaC Mini version [e.g: 2.0]: 2.11

OSX version [e.g: 10.14.6]: 11 beta4
NUC model [e.g: NUC8i7HNK]: nuc8i7hvk
Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: sn750 512g
First DIMM model [e.g: Patriot DDR4-2666 16GB]: crucial ddr4-2666 8g
Second DIMM model (if installed): crucial ddr4-2666 8g
Display port(s) used [e.g: USB-C, mini DP]: mini-dp
Display resolution(s) [e.g: 4K, 5K]: 4k 95hz
Any TB3 devices:
Any USB devices:
config. plist no changes

**Comment by dockeyZhang** [comment] 2020-08-25 00:19
I have the same issue. And suffer screen flickers.

HaC Mini version [e.g: 2.0]: 2.11

OSX version [e.g: 10.14.6]: 11 public beta2
NUC model [e.g: NUC8i7HNK]: nuc8i7hvk
Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 970 evo 512g and sn750 2t
First DIMM model [e.g: Patriot DDR4-2666 16GB]: ADATA ddr4-2666 16g
Second DIMM model (if installed): ADATA ddr4-2666 16g
Display port(s) used [e.g: USB-C, mini DP]: USB-C and HDMI
Display resolution(s) [e.g: 4K, 5K]: 4k and 1080p
Any TB3 devices:
Any USB devices: logic wireless keyboard and mouse
config. plist no changes

**Comment by goodbest** [comment] 2020-08-25 03:09
I've experienced the same thing. 
Root cause can be fixed by https://github.com/osy86/HaC-Mini/pull/319

**Closed** 2020-08-25 06:14 UTC
Labels: duplicate
