### ISSUE TITLE
HDMI output flickering after waking up

### ISSUE THREAD

**Issue by geekdada** [osy86/HaC-Mini#277] opened 2020-06-13 11:35 UTC
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**
HDMI output flickers(black screen for 1 or 2 seconds) every few seconds after waking up. Unplug and plug would solve it.

**Expected behavior**

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.9
- OSX version [e.g: 10.14.6]: 10.15.5 (19F101)
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung 870 Pro, NVME
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: None
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: DDR4-2667 16GB
- Second DIMM model (if installed): DDR4-2667 16GB
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by osy86** [comment] 2020-06-14 08:54
Duplicate of #7

**Closed by osy86** 2020-06-14 08:54 UTC
Labels: duplicate

**Comment by geekdada** [comment] 2020-06-14 14:31
@osy86 I'm aware of #7, but this issue never happened before 10.15.5.

**Comment by osy86** [comment] 2020-06-14 16:03
I think you were lucky. I don’t know what causes it and I’ve been trying to figure out but it’s definitely not related to 10.15.5.

**Comment by geekdada** [comment] 2020-06-15 05:15
Flickering did happen every now and then before 10.15.5, but it usually lasted no more than half a second, and replugging the HDMI would not solve it.

**Comment by geekdada** [comment] 2020-12-09 14:51
Using a type-c to HDMI dongle solves the problem.
