### ISSUE TITLE
UI broken after upgraded to macOS Big Sur with 2.14

### ISSUE THREAD

**Issue by errorstack** [osy86/HaC-Mini#386] opened 2020-11-15 11:15 UTC
**Describe the bug**
Wall paper, some of the system icons, borders of context menu was broken after upgraded to macOS Big Sur with 2.14.

**Expected behavior**
UI displays correctly

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.14
- OSX version [e.g: 10.14.6]: 11.0.1
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung 970 EVO 500G
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: USB-C
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94360CS2

**Modifications**
none

<img width="1920" alt="Screen Shot 2020-11-15 at 6 57 48 PM" src="https://user-images.githubusercontent.com/4124287/99183448-cf271000-2776-11eb-98f6-911f46631a17.png">
<img width="272" alt="Screen Shot 2020-11-15 at 6 57 22 PM" src="https://user-images.githubusercontent.com/4124287/99183449-d2220080-2776-11eb-84a8-dfca8301794d.png">
<img width="199" alt="Screen Shot 2020-11-15 at 6 56 53 PM" src="https://user-images.githubusercontent.com/4124287/99183450-d2ba9700-2776-11eb-8447-c343d533deb3.png">

**Comment by osy86** [comment] 2020-11-15 12:47
Duplicate of #316

**Closed by osy86** 2020-11-15 12:47 UTC
Labels: duplicate
