### ISSUE TITLE
Thunderbolt 3 firmware for NUC8i7Bxx series?

### ISSUE THREAD

**Issue by chadbailey59** [osy86/HaC-Mini#246] opened 2020-04-25 22:57 UTC
I hope you'll forgive the intrusion, but it looks like your project is the best resource out there for Hackintoshing a NUC 8 and getting the details right.

I'll keep my question brief: I have a NUC8i7BEH. It has the JHL6340 Alpine Ridge chip, which is the single-port equivalent of the JHL6540 chip in the H series NUCs. I was hoping to replicate your process for native Thunderbolt support, but I can't find anywhere to download a specific firmware for my NUC. Is there any chance that the tweaked firmware included in the HaC Mini tools here would work on my NUC? I'm happy to do a lot more legwork to make it happen, but I figured I'd start by asking the world's foremost expert. :)

**Comment by osy86** [comment] 2020-04-25 23:16
Duplicate of #241

**Closed by osy86** 2020-04-25 23:16 UTC
