### ISSUE TITLE
TV app won't play/download any videos

### ISSUE THREAD

**Issue by vnev** [osy86/HaC-Mini#257] opened 2020-05-06 19:27 UTC
**Describe the bug**
Running the TV app, it opens fine. But trying to stream/download any video doesn't work. Clicking play on a video causes the video player to open up and then instantly close. Clicking download on a video starts the download, but the download errors out at some random point during the download with error code 10024. 

Looking at Console, it looks like there are several errors from `accountsd` when the play button is pressed and the video player crashes, along the lines of `Cannot check access to a private account type: com.apple.account.CardDAV` and `Client <private> is not allowed to access accounts of type com.apple.account.CardDAV`. The TV process also fails with `Task ... HTTP load failed`. I doubt this issue has to do with network connections though, since I can stream YouTube videos and browse the internet while downloading and the download still fails while nothing else is interrupted.

Not sure if this will help but I thought I would put it in.

**Expected behavior**
Video should download/stream with no issues.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.7
- OSX version [e.g: 10.14.6]: 10.15.4
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: WD 500GB NVMe SSD
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: N/A
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 16GB 
- Second DIMM model (if installed): N/A
- Display port(s) used [e.g: USB-C, mini DP]: USB-C
- Display resolution(s) [e.g: 4K, 5K]: 2560x1440 144Hz
- Any TB3 devices: N/A
- Any USB devices: Mouse

**Modifications**
N/A

**Panic log**

**Comment by osy86** [comment] 2020-05-06 19:30
Duplicate of #131

**Closed by osy86** 2020-05-06 19:30 UTC
Labels: duplicate
