### ISSUE TITLE
Thunderbolt : no drivers loaded

### ISSUE THREAD

**Issue by Purpleman666** [osy86/HaC-Mini#336] opened 2020-09-28 09:33 UTC
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**
Everything work fine with my build except the thunderbolt 3. It says : Thunderbolt , no drivers loaded (legacy mode). But when i plug a thunderbolt device (in my case the adapter thunderbolt 3 to 2 and after the thunderbolt to firewire), informations system always says "Thunderbolt : no drivers loaded" but i can see my firewire device and adapter but they don't work. 
I've update the thunderbolt chips under windows, but nothing change. 

**Expected behavior**
If you can tell me how to make it work even there is not hotplug. Thank you.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.12
- OSX version [e.g: 10.14.6]: 10.14.6
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Sabrent rocket 1To APFS with osx
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: Samsung 970 EVO 1To with windows NTFS
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Crucial 16Gb DDR4-2666
- Second DIMM model (if installed): Crucial 16Gb DDR4-2666
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 4k
- Any TB3 devices: 
- Any USB devices: USB apple keyboard (the old white one), logitech mouse G502
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: Intel 8265

**Modifications**
Just add the bluetooth kext.

**Panic log**
No panic log

**Comment by osy86** [comment] 2020-09-28 15:56
Duplicate of #300

**Closed by osy86** 2020-09-28 15:56 UTC
Labels: duplicate
