### ISSUE TITLE
Headphone jet doesn't recognize input for iPhone earphone.

### ISSUE THREAD

**Issue by simonesgh** [osy86/HaC-Mini#235] opened 2020-04-08 11:14 UTC
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
**Describe the bug**
Headphone jet doesn't recognize input for iPhone earphone.

**Expected behavior**
I'm expecting I can see new input device once I plugin my iPhone earphone. and I can speak with the earphone.

**Configuration**
- HaC Mini version [e.g: 2.0]: latest one when I report
- OSX version [e.g: 10.14.6]: 10.15.4
- NUC model [e.g: NUC8i7HNK]: NUCi7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: some 1TB SSD
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: none
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Hyper 2666 16GB x2
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]:  no
- Display resolution(s) [e.g: 4K, 5K]: 1k
- Any TB3 devices: no
- Any USB devices: logithech union sync

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

AMD hardware decode, DW1820A bluetooth driver 

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by simonesgh** [comment] 2020-04-08 11:15
at the end, thank you for taking care my report :)

**Comment by hepto** [comment] 2020-04-08 11:16
I don't believe mics are supported - the documentation describes this as 'no headsets' on both analogue ports, and technically that means the mic part of the 3.5mm jack.

**Comment by osy86** [comment] 2020-04-08 15:16
Duplicate of #5

**Closed by osy86** 2020-04-08 15:16 UTC
Labels: duplicate
