### ISSUE TITLE
Patching OSX install usb fails at "Running Package Scripts"

### ISSUE THREAD

**Issue by errorstack** [osy86/HaC-Mini#89] opened 2019-10-23 13:22 UTC
Describe the bug
completely the same with the closed issue #63 , but what I used is the latest version 2.2 that released on Oct 13.

After following clean install directions while building a new install on another machine, the patcher failes at "Running Package Scripts".
I notice that there is an efi drive mounted on the desktop with an ESP folder, that seems to be symlinked to itself, so it just keeps opening itself forever.

Expected behavior
Patching should complete

Environment:
Running OSX version: OSX Catalina on patching pc
Target drive OSX version: OSX Catalina from app store
HaC Mini installer version: Latest test release

Additional context

Logs

**Comment by osy86** [comment] 2019-10-23 15:33
Logs please.

**Comment by errorstack** [comment] 2019-10-23 16:41
I've solved this problem by disable SIP for macOS Catalina. Thank you:) @osy86

**Comment by osy86** [comment] 2019-10-23 17:04
Let me keep this open so I can try to make the installer work with SIP.

**Comment by osy86** [comment] 2019-10-27 03:06
I've tried the installer on a brand new 10.15 VM and was not able to reproduce. However, I suspect the mistake you made was not having a GUID formatted disk. I've added a check for that in the future. If you posted logs, we would know for sure. However, since there is no issue and I cannot reproduce, I will close this.

**Closed by osy86** 2019-10-27 03:06 UTC
Labels: installer
