### ISSUE TITLE
Flicker if WhateverGreen is enabled for LG 5K thunderbolt display[Apple Resell Only]

### ISSUE THREAD

**Issue by JeffreyVIP** [osy86/HaC-Mini#172] opened 2020-01-25 12:32 UTC
WhateverGreen is enabled by default in HaCMini installer, but there is flicker when using LG 5K thunderbolt display [Apple Resell only].

Conditions:
- BIOS version: 0058
- Thunderbolt mode: Flicker in both Legacy and Native mode
- MacOS version: 10.14.6
- Only LG 5K thunderbolt display connected, no HDMI display connected

Warning: 
THERE IS NO FLICKER if there is another HDMI connected when using LG 5K thunderbolt display.

**Comment by osy86** [comment] 2020-01-25 15:43
Seems to be #7

**Comment by osy86** [comment] 2020-01-25 15:44
Can you see if setting the display options to be rotated 180 degrees solves it?

**Comment by JeffreyName** [comment] 2020-01-25 15:57
> Can you see if setting the display options to be rotated 180 degrees solves it?

Glad to make the test, but instruct me how to remove WhateverGreen after test, otherwise I need to re-install the whole system.

**Comment by osy86** [comment] 2020-01-25 15:58
Re-run hac mini installer and deselect WhateverGreen

**Comment by JeffreyName** [comment] 2020-01-25 16:00
> Re-run hac mini installer and deselect WhateverGreen

No, this method doesn't work, de-select means ignore.

**Comment by osy86** [comment] 2020-01-25 16:00
Yeah the issue isn’t related to WG I’ve found

**Comment by JeffreyName** [comment] 2020-01-25 16:01
> Seems to be #7

I think it is different issue. If WhateverGreen is removed, there is no flicker, even after wake-up from sleep.

**Comment by osy86** [comment] 2020-01-25 16:02
> > Re-run hac mini installer and deselect WhateverGreen
> 
> No, this method doesn't work, de-select means ignore.

Sorry what do you mean this doesn’t work then? You still see the WG kext in your EFI?

**Comment by JeffreyName** [comment] 2020-01-26 06:17
> > > Re-run hac mini installer and deselect WhateverGreen
> > 
> > 
> > No, this method doesn't work, de-select means ignore.
> 
> Sorry what do you mean this doesn’t work then? You still see the WG kext in your EFI?

Can you kindly instruct me on how to mount EFI partition?

**Comment by osy86** [comment] 2020-01-26 06:19
The easiest way is to use [Clover Configurator](https://mackie100projects.altervista.org/download-clover-configurator/) (it's fine that we don't use clover, just use the EFI mounting tool that it comes with)

**Comment by JeffreyName** [comment] 2020-01-26 14:08
> Re-run hac mini installer and deselect WhateverGreen

Re-run hac

> Can you see if setting the display options to be rotated 180 degrees solves it?

No. but flicker frequency decrease.
Every time I re-run HacMini to select or de-select WhateverGreen, first reboot after installation won't succeed, a short power button press will power off NUC, 2nd boot will be successful.
Always, there will be no Apple booting logo until seeing login window.

**Comment by JeffreyName** [comment] 2020-01-26 14:17
> Sorry what do you mean this doesn’t work then? You still see the WG kext in your EFI?

De-select will remove WG kext, HaCMini Installer GUI mislead me.

**Comment by osy86** [comment] 2020-01-26 16:56
Does removing WG fix the issue?

**Comment by JeffreyName** [comment] 2020-01-27 03:38
> Does removing WG fix the issue?

Yes!!

**Comment by osy86** [comment] 2020-01-27 03:59
Can you try having WG installed but also disable Intel IGPU in BIOS? Does that make a difference?

**Comment by KrisCris** [comment] 2020-01-27 04:52
So is there any drawbacks with WG removed?

**Comment by osy86** [comment] 2020-01-27 05:44
WG fixes an issue where if you boot verbose it sometimes panics if too many messages get printed. It also enables hardware video encoder/decoder. It also sets the model string but that’s not important.

I don’t think WG is the cause of it because the flickering happens in some cases without WG (certain resolutions). I think something in WG might be increasing the cases where it does happen.

**Comment by KrisCris** [comment] 2020-01-27 05:58
> WG fixes an issue where if you boot verbose it sometimes panics if too many messages get printed. It also enables hardware video encoder/decoder. It also sets the model string but that’s not important.
> 
> I don’t think WG is the cause of it because the flickering happens in some cases without WG (certain resolutions). I think something in WG might be increasing the cases where it does happen.

Yes, it doesn't help in my case.

BTW, I think the sidecar feature is also disabled with WG uninstalled, right? Since my iPad showed nothing but black screen when WG was disabled.

**Comment by osy86** [comment] 2020-01-27 06:27
Oh I think that’s because sidecar requires the hardware video encoder.

**Comment by KrisCris** [comment] 2020-01-27 06:31
> Oh I think that’s because sidecar requires the hardware video encoder.

And because of that, the sidecar won't work when choosing the AMD one as codec in latest installer.

**Comment by osy86** [comment] 2020-01-27 06:36
I see, that’s interesting. That also explains why Apple’s support docs for sidecar don’t show models with AMD encoder as supported.

**Comment by lmshsqlc** [comment] 2020-01-27 06:39
> I see, that’s interesting. That also explains why Apple’s support docs for sidecar don’t show models with AMD encoder as supported.

But Mac pros must support sidecar right? If not using IGPU, T2 chips?

**Comment by KrisCris** [comment] 2020-01-27 06:43
> > I see, that’s interesting. That also explains why Apple’s support docs for sidecar don’t show models with AMD encoder as supported.
> 
> But Mac pros must support sidecar right? If not using IGPU, T2 chips?

And someone had made sidecar working without IGPU after adding some boot-args (hackintosh).

**Comment by JeffreyName** [comment] 2020-01-27 12:10
> Can you try having WG installed but also disable Intel IGPU in BIOS? Does that make a difference?

Tried, No difference.
If WG installed and iGPU disabled, there is flicker, but there is Apple boot logo.
There is no apple boot logo if WG removed(first screen is login window after booting).

**Comment by KrisCris** [comment] 2020-01-27 13:59
> THERE IS NO FLICKER if there is another HDMI connected when using LG 5K thunderbolt display.

Interesting, when I have 2 displayPort output with 1 HDMI output, no display is flickering.
![Screen Shot 2020-01-27 at 9 50 51 PM](https://user-images.githubusercontent.com/38860226/73180415-4344e880-4150-11ea-9d73-0f545a04d2b2.png)

**Comment by osy86** [comment] 2020-01-27 17:37
> > > I see, that’s interesting. That also explains why Apple’s support docs for sidecar don’t show models with AMD encoder as supported.
> > 
> > 
> > But Mac pros must support sidecar right? If not using IGPU, T2 chips?
> 
> And someone had made sidecar working without IGPU after adding some boot-args (hackintosh).

Only the 2019 Mac Pro supports it https://www.apple.com/macos/catalina/docs/Sidecar_Tech_Brief_Oct_2019.pdf so maybe some trick there.

Can you link to the hackintosh boot-args?

**Comment by KrisCris** [comment] 2020-01-28 04:22
> Can you link to the hackintosh boot-args?

https://fangf.cc/2019/10/14/noneigpusidecar/
It's in Chinese, so possibly hard for you to read.
He says the smbios should be set to `18,3` or `imac19,1`, and add boot-args:`shiki-id=Mac-7BA5B2D9E42DDD94`, `shikigva=40`, then it's done.

Someone commented succeed while still some failed, so not sure if it's still works since I didn't try that.

Also, I had seen similar approaches before when googling but with a different `shikigva` value, maybe you can find that on google.

**Comment by osy86** [comment] 2020-06-24 03:29
Closing as duplicate of #7

**Closed by osy86** 2020-06-24 03:29 UTC
Labels: duplicate
